### ISSUE TITLE
What's up

### ISSUE THREAD

**Issue by TwiN** [thecsw/memeinvestor_bot#137]
What's going on? 

Everything completely stopped moving forward. Unless the bot gets back online, we won't be getting more people into this project -- even we are forgetting about it.

**Comment by rickles42** [comment]
Hey there @TwinProduction! We're definitely still hard at work--if you check out the project [network page](https://github.com/MemeInvestor/memeinvestor_bot/network), you'll see there's a lot of activity. We're just mostly working in branches now instead of directly in `master`, like good devs 😄 . So maybe it doesn't show up as much.

My goal is to finish our rework and get the bot back up and running tonight.

**Comment by thecsw** [comment]
Yeah, we were working on isolated branches instead of pushing directly to master.

**Comment by rickles42** [comment]
@TwinProduction We just officially completed the re-launch! Huzzah!

**Comment by TwiN** [comment]
@thecsw @rickles42 Oh, my bad! I completely neglected looking at the branches. I'm glad the project is still ongoing.

As soon as I'm done moving out/painting my new appartement, I'll jump right back in!
