### ISSUE TITLE
Make !create optional

### ISSUE THREAD

**Issue by robalb** [thecsw/memeinvestor_bot#149]
!create and !broke are not necessary, when someone invests for the first time the account can be created automatically, and also the recovery after a bancruptcy can be done automatically. By doing this the bot could save on some api calls

**Comment by rickles42** [comment]
Hmm, you're technically right that these could be made automatic, but I'm not sure what behavior makes the best game. For example I don't think I like the idea of _automatically_ going through bankruptcy--I think it takes some of the emotional impact out of it. But creating an account probably makes sense to do automatically.

**Comment by robalb** [comment]
Hey what about making the bancruptcy operation on a dedicated page on the website? when you go bancruptcy, the bot answer to your investments could be: you don't have enough moneys, recover your account on memes.market/bancruptcy/?u=USERNAME. and on the page we can make a big button or something like that. Since a bancruptcy recovery is not a dangerous operation, we can make apis for it without requiring authentication

**Comment by Zonico6** [comment]
Hey guys, I think too that it would be a great idea to neglect !create, however I think that the !broke is a really good solution since it's not the end of the world but you still need to take some action and foremost publicly accept and admit your bankruptcy. I personally would be a little intimidated by an hyperlink and links on mobile are annoying too.  
What would you guys think about a penalty when declaring bankruptcy like 12 hour timeout or so?

**Comment by thecsw** [comment]
A very nice issue. I'm okay with adding automatic create when investing for the first time. Also, automatic bankruptcy takes out the emotions from the operation, so I would leave the command to manually declare bankruptcy. Also, as @Zonico6 pointed out, it would be sweet to add some kind of a `broke` command cooldown.
