### ISSUE TITLE
malformed api calls are accepted

### ISSUE THREAD

**Issue by robalb** [thecsw/memeinvestor_bot#185]
malformed api calls that doesn't have a slash before the method keyword are handled as correct by the api.
example: `https://memes.market/apicoins/total` returns the same as the correct `https://memes.market/api/coins/total`. This works with all the apis methods

**Comment by rickles42** [comment]
I think this is due to the way we're configuring the [proxy plugin](https://caddyserver.com/docs/proxy) for the Caddy server, which redirects any requests starting with `/api` to our API server. Theoretically we could fix this by instead proxying `/api/` but I don't see any examples like that in their documentation, so it feels weird to resort to it. I'll investigate further.
