### ISSUE TITLE
Fix dramatic dips in last day of website charts

### ISSUE THREAD

**Issue by rickles42** [thecsw/memeinvestor_bot#192]
Currently, the charts often take a misleading dive in the last column, since they're showing data from a partial day. I think we should just display data for full days, or else restructure the chart to show rolling stats on last 0-24hrs, 24-48hrs, 48-72hrs, etc.

**Comment by robalb** [comment]
what do you mean for rolling stats?

**Comment by rickles42** [comment]
I just mean instead of having the last datapoint in the chart represent [investments made on July 20], the last data point could represent [investments made in the 24hrs prior]. So each data point would still represent a whole day, just not a whole day aligned on calendar day boundaries.

**Comment by robalb** [comment]
it would be really cool if the apis returned the data required by the graph in an array, since at the moment the website has to make 14 api calls each time to `/investments/total?from=--&to=--` and `/investments/amount?from=--&to=--`. With the array method it would also be possible to display the data of all the season, something like this
![screenshot_2018-07-24 meme investor bot](https://user-images.githubusercontent.com/11277482/43135041-586a3d74-8f44-11e8-829b-2f45b7a3adcd.png)

**Comment by rickles42** [comment]
Funny, I was just playing around with the chart to try out the same thing! The animation when it loads a whole month of data day by day is kind of neat IMO.

It's not really a problem for the server to receive so many small requests, but I hear you that it's probably a pain to write the JS for. As a separate Issue I'll see if I can update the API to return this data in a batch. But is there a quick fix for this Issue (incomplete days) that you can do with the current API?
