### ISSUE TITLE
Allow for !invest all

### ISSUE THREAD

**Issue by DanielZendejas** [thecsw/memeinvestor_bot#249]
Hi, thanks for the really cool project.

I noticed that for specially good memes people usually ask for `!balance` and then issue a second command with `!invest` all of their memecoins. Would it be a good idea to implement keywords like `all` or `half`? This way we could achieve the same with less calls to Reddit's API.

In case you find this to be a good idea I'd be glad to familiarize myself with the codebase and write the change myself.

**Comment by thecsw** [comment]
Thanks for your issue! You would be surprised to hear that we get this suggestion almost daily. This issue is a duplicate of #75, #220, and #241. We also discussed this feature on our forum.

[First post](https://old.reddit.com/r/MemeInvestor_bot/comments/91ue12/suggestion_can_we_make_invest_all_an_option/)

[Second post](https://old.reddit.com/r/MemeInvestor_bot/comments/9fdhr8/suggestion_ability_to_invest_all_in_my_balance/)

[Third post](https://old.reddit.com/r/MemeInvestor_bot/comments/93hain/why_no_invest_all_or_similar/)

We want people to have an experience of checking their balance. Investing is not gambling to say "All in".

If you want to contribute, you can start solving issues or adding your own features via pull requests.

I am closing this issue as a duplicate.
