### ISSUE TITLE
Request: the OP will get a small percentage of investments as a reward for their post

### ISSUE THREAD

**Issue by ometrist** [thecsw/memeinvestor_bot#43]
I'm assuming there is no insider trading. If there is no insider trading, it means there is less motivation for an OP to put out a good meme. If theirs is doing really well, and they are unable to invest in it, it benefits everyone besides the OP. I'm thinking the poster should get 1% of whatever investments are made or less. 

It also gives OP a reason to not delete their meme if it starts doing really well. If it stays up, then more people will invest and OP will benefit. I'm not sure exactly what happens though right now if someone takes down a post that people just put a lot of investments into though.

**Comment by thecsw** [comment]
Will add this to TODO list!
Thanks

**Comment by sreetamdas** [comment]
Agreed, the karma doesn't matter for anything in the Economy, the OP should be rewarded for quality meme templates.

**Comment by TwiN** [comment]
@thecsw @ometrist What if OP doesn't have an account? Should the user be automatically created?

**Comment by ometrist** [comment]
Whatever is easier to code, I'm happy with not giving them anything if they dont have an account

**Comment by Ex-Ex-Parrot** [comment]
Should something of this nature be implemented what would be the impact in the future if there are market leaders dominators?

The only thing that makes sense to me personally, is that should OP's post be successful- the returns back to OP should be based off his/her current balance.  Should it reach a point where there are individuals investing million/billion/+ any small percentage of gain on those would catapult them into a higher bracket. Making investing from 1000 to start moot.

It really is an excellent idea if OP can't invest in his own post, but if there isn't a simple enough alternative would it be all that bad if OP could just invest in his/her own post? It seems reasonable to allow one to bet against one's self.

**Comment by ometrist** [comment]
@Ex-Ex-Parrot I see why you'd be concerned, but i'm sure you wouldn't mind giving ≤ 1% of investments (or ≤ 1% of winnings), you could even make it 0.1%. Considering where the new function is likely headed, maximum investment amount allowed or maximum return % allowed, I don't see the economy ever reaching a point where there are only a couple people who own 99% of the market anytime soon. 

If that is the case where the top 1% of users own 99% of MemeCoins, this may help even the market out by redistributing wealth. Either way we should prevent that situation from happening again in the first place, as opposed to assuming it happens. 

Lastly, I'd say it wouldn't be the end of the world if the OP of a successful post was catapulted/trebuchet'd into a higher bracket, it was earned. 

>   It really is an excellent idea if OP can't invest in his own post

I really never understood this. The only reason why I thought this was a good idea is to make a joke about insider trading, that's it. That's the only reasoning I could put behind doing this. Can someone explain why this was such a good idea in the first place?

**Comment by Ex-Ex-Parrot** [comment]
@ometrist

Sorry if my sentences are a bit goofy, on my phone posting now. It's not that I or anyone would have a problem giving a small amount, even fraction at that, to OP for content posted/investment returns I have the problem with. It's that later in the market it becomes a problem that anyone starting out is better off posting instead of investing since even fractions of hundreds of thousands/millions/billions is better than investing.

So anyone starting an account and investing with 1000 is wasting time if they could post and get .01% of returns on a single investment of someone putting up over a billion. I would have no problem if I gave 1-100 trillion if I had 100 quadrillion, the problem is that someone who just started and made a post got 4-5+ days worth of investing ahead of anyone else.

I'll admit that ideally it's better in the end for people to post content to the subreddit rather than being there for the sake of the bot, so this is all just discussion.  But as Thecsw said in the past- it's incredible how much work and theorizing is going into a marketplace/trading platform for memes lmao.

**Comment by ometrist** [comment]
> it's incredible how much work and theorizing is going into a marketplace/trading platform for memes lmao 

x 10  lol 

I see what you're saying now though about it being way bette to post content than ever !invest if you're just starting out. If we over-encourage people to post memes over !investing, then we're setting ourselves up for a subreddit full of garbage posts, which benefits nobody. 

Rewarding OPs based on their current balance could be the solution, or maybe we can set up a cosmetic reward system for OPs

**Comment by tsiq-swyx** [comment]
didn't someone try to make a nasdanq earlier? then got sued by actual nasdaq? lol

**Comment by rickles42** [comment]
Closing this issue as the idea has not received broad support. It's a cool concept but I don't see us pursuing it any time soon. Please keep the suggestions coming though!
