### ISSUE TITLE
All in

### ISSUE THREAD

**Issue by NelsonZC** [thecsw/memeinvestor_bot#75]
Either a simple !allin or !invest balance to streamline betting all of your meme coins on one meme

**Comment by ometrist** [comment]
It would be pretty cool to go all in, like we're in vegas, but i'm not a big fan of this for a couple reasons

1) more coding work 
2) people would do this frequently and go bankrupt more frequently due to going all in (like for example if the OP deleted the post after someone went all in). Let's see what others think

**Comment by NelsonZC** [comment]
Those are good points but counter argument
1. I’m willing to bet they have thought of it and discussed it, if not now it’s out there
2. They’re just meta internet points that really mean nothing so going all in is just another way to have fun and add risk.

**Comment by TwiN** [comment]
@NelsonZC great idea, but investment is not poker.

Adding such a feature would be encouraging bad investment practices, even if they're just internet points.

We're trying to make the investment system as realistic as possible -- meaning that we (or at least, I) want to get as close as possible to this being a simulation.

**Comment by NelsonZC** [comment]
@TwinProduction understandable thanks for the feed back

**Comment by thecsw** [comment]
Thank you, @TwinProduction. This is not poker to have all-in strategy. I will close the issue for now.
