### ISSUE TITLE
Meme success should be determined by a time series, not by a comparison to initial vote count. (+other suggestions)

### ISSUE THREAD

**Issue by hipp013** [thecsw/memeinvestor_bot#84]
_Let me start out by pointing out I'm an Economics major in university with an extensive background in statistical economics, not that this makes me an expert by any means; I just hope to establish some sort of credibility for my claims._

&nbsp;

## Preface

The investor bot could be a great tool to keep users active on the subreddit, _if implemented correctly_. 

Let me ask you a question: do you want the bot to just be a short-term gimmick, or a long-term tool to keep users engaged and active in the community? 

Given that the creator has developed [a beautiful website](https://memes.market/) for the bot, I'm going to assume the answer is the latter. If this is the case, then something needs to change. 

## Problems

There are two separate issues that must be addressed: the **formula** and the **investing system**. The formula is self-explanatory, but when I say "investing system", I refer to two fatal flaws: users can invest **as much as they want**, and **any post can take an infinite amount of investments.** 

To fix the investing problem, both of these flaws must be addressed. But first, I'd like to talk about the formula.

&nbsp;

## Formula Enhancement

The current main problem with the formula is with the first step in the two-step process; specifically, that it determines success by comparing final with initial. As mentioned, this leaves a large hole for users to take advantage of, specifically by investing when a post is at 1 or 2 upvotes and (at worst) having it naturally increase into the teens. In fact, even the smallest upvote increase possible, from 1 to 2, is considered successful according to the bot, when it clearly isn't. 

My proposal is to deem a meme successful by the _rate_, not the amount, at which upvotes increase, compared to an established baseline of success (the value of which should be determined from real, human analysis of "successful" and "unsuccessful" threads). Specifically, the bot should conduct a **time series** on the amount of upvotes, tracked every 30 minutes to determine whether the upward trend is greater or less than a certain baseline. 

It would be way more beneficial to use a time series, a method of calculation that is [actually used in the stock market](https://en.wikipedia.org/wiki/Time_series), as opposed to an algebraic function that allows for disproportionate, spastic growth for investments made at the post's creation.

&nbsp;

## Investment Changes:

To correct those two points of failure I mentioned above, I propose a 50,000 coin cap on investments per user per image (and to prevent using multiple !invest comments to get around this). This prevents users from investing as much as they can on an image to reap infinite benefits.

Secondly, I propose a net investment cap per image ("net cap") at *any given time*; i.e. if a meme currently has a total of 1,000,000 coins invested in it, then no one else can invest until one of those investments has expired and the total amount of coins invested has decreased below the cap. This means the opportunity to invest is no longer infinite, leading to a reduction in exponential growth. 

&nbsp;

---

I understand the mods are fully competent and able to handle the situation on their own, however if they are open to the idea of discussing any means to stabilize the economy, I'd be more than happy to reach out and toss some ideas back and forth as well as assist in crafting an effective time series system.

(Also the figures of 50,000 and 1,000,000 are just examples and not set in stone.)

&nbsp;

Please let me know your thoughts. I will be cloning the source code and testing different formulas to show the benefits of a time series.

**Comment by jimbobur** [comment]
I've been working on/fine-tuning a solution for this exact problem since Sunday; We're acutely aware of the effect it's had on the economy.

The investment capping ideas are interesting and also, in my opinion, a good idea for helping to further regulate the economy. A time series is also an interesting avenue of exploration, although it will depend on the feasibility of adding the extra overhead of repeatedly collecting upvotes over time; as the other devs will tell you, we're already running into the request frequency limits of the reddit API.

I won't go into too many details on the proposed solution yet, since it's still very much in development, but broadly-speaking, the behaviour of the most recent version is such that:

- **investing at low upvotes**: get nothing back till you reach the lose/nothing threshold, but once you do, it's not many more upvotes til you start making profit.
- **investing at high upvotes**: enter the 'lose zone' (get back a sub-multiple of your investment) after not much gain in upvotes, but have to gain much more upvotes before you start making any profit.

To put some numbers to it, a recent **example** configuration gave:
#### invest at 1 upvote:
lose/nothing threshold: 552
win/lose threshold: 614
So here you get nothing at all unless the post gets above 552 upvotes, but you start winning only 62 upvotes later. The 'lose zone' is narrower for smaller starting upvotes, but you have to gain a fair amount more than the initial upvotes to begin with in order to get anything back at all.
#### invest at 400 upvotes:
lose/nothing threshold: 1180
win/lose threshold: 1472
#### invest at  5000 upvotes:
lose/nothing threshold: 5001
win/lose threshold: 12,442
So here you're pretty much guaranteed to get back some sub-multiple of what you invested, but you won't start making profit till until you reach 12k upvotes.

(I put **example** in bold above to stress that these figures are in no way final.)

In addition, here's a graph of the return as a function of final upvotes for different starting upvote values to maybe illustrate what I've said above a bit better (I hope):
![image](https://user-images.githubusercontent.com/34943023/41050858-767415fa-69ac-11e8-9f01-eef9e280b9e3.png)

**Comment by rickles42** [comment]
I will definitely leave all the investment formula stuff to you experts, but please don't lose sight of the fact that users will be more engaged if they can easily _understand_ the formula. Simplicity is powerful. I'd even go so far as to say that between a simple formula that works fine, and a complex formula that works great, the simple formula might be better for the community.

**Comment by rickles42** [comment]
@hipp013 If you do clone the project, I think you'll quickly find it's difficult to figure out how to get started and launch your own test bot. I'm trying to alleviate that problem piece by piece, but for now I recommend looking at my branch [config](https://github.com/rickles42/memeinvestor_bot/tree/config) which has some configuration improvements and edits to the README for getting started.

**Comment by hipp013** [comment]
@jimbobur That certainly looks like an improvement over the current system. I obviously don't know what this new formula is, but at first glance, it looks like the return factor variable is brought to the power of some fraction of x so that the return factor is exponentially influenced by the size of the initial upvotes. If I'm right, great idea. If I'm wrong, then awesome idea. 

One question: will the math for this new formula be open sourced as well? Because if you want my opinion, it should stay closed. It's one thing to open source _code_, but _math_ can be reverse-engineered and manipulated by any average person with just a pen and paper. It might not be too difficult for someone to track the investor bot's comments and get a close approximation, but that's still more manipulation-proof than publishing the formula for all to see.

I also had another question about the math. I know the current formula has flaws and this can just be discounted as one of them, but I was curious about the rationale for this part of it. In the first step of the calculation function, the formula for x is `x = 1 + ( [final - initial] / initial )`. Obviously the formula `( [final - initial] / initial )` calculates the percentage increase from initial to final, but I'm confused as to why 1 is added; when you add 1 (essentially equal to `initial / initial`), it readds the `initial` that was subtracted from `final`, so essentially the entire formula for x can be condensed to `x = final/initial`. Was this just an error, or is there something I'm missing? Could it have something to do with handling a situation where someone invests in a post when the vote count is 0?

edit: accidentally closed issue

**Comment by hipp013** [comment]
@rickles42 Rest assured I have no intention of making a bot to test the math; your team is far more capable of creating a bot than I am, and I've seen the obstacles you guys have run into trying to get the bot fully functional. 

I only plan to take the calculation function and tinker with the code, supplying sample data in place of real user interaction.

**Comment by hipp013** [comment]
@rickles42 Thanks for the warning! Rest assured I have no intention of making a bot to test the math; your team is far more capable of creating a bot than I am, and I've seen the obstacles you guys have run into trying to get the bot fully functional. I'm a math guy, not a bot guy. :P

I only plan to take the calculation function and tinker with the code, supplying sample data in place of real user interaction.

**Comment by jimbobur** [comment]
@hipp013 
> if you want my opinion, it should stay closed. It's one thing to open source code, but math can be reverse-engineered and manipulated by any average person with just a pen and paper.  

Yes, some of the devs are of the same opinion for more or less the reasons you've stated.  

>  Was this just an error, or is there something I'm missing? Could it have something to do with handling a situation where someone invests in a post when the vote count is 0?  
  
Looking back over the function, I think it was something carried over from when I was experimenting with the formula outside of the code before writing the calculation algorithm which could indeed be simplified to `x=final / initial`. Looking at some more up-to-date numerical messing around I did outside of the code, it appears I've actually made this simplification. As for the `initial votes = 0` case, there's now an if statement in the calculation to avoid the DIV0 error if by simply setting `x = final` in this case (i.e. clamping the denominator of `final / initial` to 1).

**Comment by rickles42** [comment]
> if you want my opinion, it should stay closed. It's one thing to open source code, but math can be reverse-engineered and manipulated by any average person with just a pen and paper.

My humble vote is for openness. We should preserve the algorithm as public knowledge. A well-designed algorithm can be resistant to manipulation, and keeping the algorithm secret would kill the chances of anyone spotting issues with it and improving it. For example, @hipp013's great analysis and involvement here would have been difficult or impossible if the algorithm had been secret from the start.

Cryptography is a great example of a system that's manipulation-resistant by design, despite the fact that the design itself is public knowledge. Hiding the design is "security through obscurity," which is not really security at all.

**Comment by hipp013** [comment]
@rickles42 

>Cryptography is a great example of a system that's manipulation-resistant by design, despite the fact that the design itself is public knowledge. Hiding the design is "security through obscurity," which is not really security at all.

I agree that the best way to improve a product is to get accurate feedback from the most people possible. There are points for both sides, and I will support your side also. Open sourcing the math allows for _everyone_ to report bugs, not just a select few approved users; essentially, more eyes = more scrutiny = more improvement. Furthermore, should any new formula be flawed in any way, users can learn from your work and come up with what could be an even better formula in the future, tying back into my first point about more eyes = more improvement. This could lead to further economic stability to a point that might not have been possible had the math not be open sourced. And as you stated, even though math can be open sourced, with a few iterations of a new formula it may be possible to make a formula so robust that it'd be difficult for the average person to manipulate. Besides, should you guys implement any sort of investment cap like I mentioned in the OP, this would make it much harder to generate exponential returns even if someone found the most efficient way to generate coins.

As I said, there's points for both sides, and @rickles42 brings up an excellent point that has actually swayed my opinion from "keep the math private" to "I'm not sure". 

Of course this entire decision is up to you guys. I hope I'm not overstepping here, but if ever in the future the team needs a fresh pair of eyes to take a look at the math, I have a ton of ideas. I take particular interest in the activities and workings of the stock market and would be more than willing to offer my help if ever needed. Don't hesitate to reach out.

**Comment by nickmahdavi** [comment]
Just leaving my thoughts here, feel free to respond.

**1. Investment cap is flawed**

To put a hard cap on the amount of coins per post is, in my opinion, a **bad idea**. Consider a user that has grinded to get to 1,000,000,000 coins. 50,000 coins, even with an unbalanced formula that gives inflated returns, will return _nearly no profit at all, compared to the total amount of coins_. 

I propose, therefore, a cap _based on the user's current amount of coins_ (say, 10% or so). This should be sufficient to keep investors from regularly tripling or so their coins (such as u/genericusername), but should allow a good amount of return. To balance this with the users with smaller amounts of coins, one could use one or more of the following: a) cooldown time, increasing as the user gets richer; b) a regular reset, once a month or so, with the highest users being rewarded with cosmetics or legacy perks; c) diminishing returns as the user gets richer. These should help keep the economy balanced over time, as well as keeping it fun.

**2. Formula should combine hard-set limit of score change and proportional change**

Simply judging an investment by the rate of change is good. However, users should be rewarded for prospecting memes and investing early, rather than jumping on bandwagons. A user from r/all should be able to turn a fine profit just by investing as the meme hits the front page. The post should continue to grow for the next day or so, and the user gets low-effort coins.

Perhaps we should try and circumvent this by combining, somehow, the amount of upvotes and the rate at which they grow.



For what it's worth, I support keeping the code open-source; it'll help users suggest ideas, as well as promoting trust. I can see some users possibly scraping MemeEconomy for advantages, if we switch to a growth-based formula, but the benefits should outweigh the losses.

I do know a fair bit of Python, please let me know if you need any assistance with bugfixes or the like. That's all, thanks for reading.

**Comment by rickles42** [comment]
@qwertios said:

> I do know a fair bit of Python, please let me know if you need any assistance with bugfixes or the like. That's all, thanks for reading.

Thanks for your kind offer! Everyone is encouraged to fork the repo and submit a pull request with fixes to any of our issues (or to any new issues you find or enhancements you care to make). Or if you aren't familiar with git/GitHub, feel free to just send me some code and an explanation, and we can review the code offline.

**Comment by rickles42** [comment]
@jimbobur is continuing to experiment with a revised returns formula. We're still trying out different ideas but we're seeing promise in an approach that mimics small-cap/mid-cap/large-cap stocks. It makes low-upvote memes high-risk/high-reward (like penny stocks) and already-established memes a safe but not-very-profitable bet.

**Comment by rickles42** [comment]
Hi all,

I'm closing this Issue since we've made a number of significant changes to the formula since last month. However I really appreciate your detailed feedback, and I've made note of a few suggestions to keep in mind for future revisions to the formula:

- Consider some kind of limitation on the amount of investment that can occur, as a way to slow inflation.

- Consider return formulas that aren't only based on (initial upvotes) and (final upvotes), but that also take the intermediate behavior into account.

As always, feel free to fork the code, play around with it, suggest improvements, etc. We even have a few useful scripts these days that help you visualize the behavior or the formula (`formula-visualizer.py` and `formula-test.py`).

Thanks again!
