### ISSUE TITLE
Include updated balance in investment results posts

### ISSUE THREAD

**Issue by rickles42** [thecsw/memeinvestor_bot#91]
Today we tell users how many MemeCoins they gained/lost. If we also (or instead) told them their new balance, we could save users some mental math or a !balance request.

**Comment by ometrist** [comment]
I'd also add that if a person doesn't have enough MemeCoins for an investment, then instead of saying something like 'you do not have enough MemeCoins for this investment' 

the bot can add in the user's current balance & active investments so that the user doesn't give the bot more commands in response?
