### ISSUE TITLE
Bot ignoring active transactions after 4 hours

### ISSUE THREAD

**Issue by TwiN** [thecsw/memeinvestor_bot#95]
#88 introduced a pretty big bug.

One of my investment was not processed at all after 4 hours.

![](https://twinnation.org/api/screenshots/2018-06-09_170928.png)
[direct link](https://www.reddit.com/r/MemeEconomy/comments/8psdey/quick_investment_buy_and_profit/e0dnfr3/?context=3)

It's fine to ignore old `!invest` commands, but active investments should not be ignored.

At worse, updating the bot's comment after 4 hours could be skipped, as long as the user's balance is updated on the database.

I think we should rework the way we're dealing with the way `!invest` commands are processed: Even if the bot hasn't commented, the investment should be registered in the database.

That would prevent the bot from being inaccurate due to the limitations of Reddit's API.

**Comment by thecsw** [comment]
That's the problem of inbox. You see, when we loop with stream comments generators, everything is in chronological order but inbox does something really weird. When you have 100 new inbox messages and you go through them. praw doesn't just make a queue and add the new messages to list, it just uses stack so if we have a huge number of messages, bot will miss the old ones. I think we should go back to streaming comments. And your issue is really strange too. We never miss return investments, they are working differently. HMMMM. Will investigate

**Comment by rickles42** [comment]
Just to clarify, this issue is _not_ being caused by #88. The `calculator` agent was unchanged by that, and this is an issue with the calculator not spotting these matured investments or something. Change 88 only affects the initial processing of the `!invest` command.

**Comment by rickles42** [comment]
@thecsw I don't think this is a problem with inbox, either. It looks like `bot` recognized an `!invest` command and responded to it, which is the only part that bad inbox handling would break (I think).

The problem is that either `bot` failed to add a new `Investment` to the database, or that it did add one, but something went wrong with `calculator` and it either couldn't pull out the investment, couldn't reply, or something.

**Comment by ghost** [comment]
I confirm that this happening to me as well. It's been 9 hours. I went all in and the bot still shows my balance as 0 and still says I have 1 active investment so it has definitely registered the investment.

**Comment by Ex-Ex-Parrot** [comment]
I will admit I've noticed quite a few people are concerned that their investments won't go through/lost in an attempt to reach the billion point before the economy resets.

Any word on the balances updating? That way I can reach out to or assure anyone on the subreddit I notice asking about it. 

Admittedly I went all-in to try to reach the quintillion so I certainly don't fall into this catagory lol. The programmers have done a wonderful job thus far, so I think the reset in general is going over well with the subreddit and everyone is pretty excited. Or rather, I say that because I've seen little serious outcry against the reset.

**Comment by ghost** [comment]
Maybe it has to do with the reset comment footer?

**Comment by PseudonymPatel** [comment]
what if we had a dictionary, and every time someone made an investment:
1. it would add a link or reference to that person’s entry in the dict, along with a time 
 Ex. `{”username” : (“reddit.com/comment/...”, x), “user2” : (“reddit.com/comment/2...”, y), ...}` where x and y is time (GMT) when user invested.
2. then every z amount of time (maybe 5 minutes), it would iterate over the dict to see what is over 4 hours old,
3. then evaluate the transaction/make sure transaction evaluated and remove it from the list.

This is just an idea, it might require a huge overhaul or something, but it should work as long as there is persistent storage.

**Comment by TwiN** [comment]
## Update

After 20 hours, the comment has been updated and my MemeCoins are in.

Though we might still want to consider the following:

> At worse, updating the bot's comment after 4 hours could be skipped, as long as the user's balance is updated on the database.

**Comment by rickles42** [comment]
This was addressed with #96. The `calculator` agent was choking on his really big transactions and not getting to anyone else's transactions. We updated `calculator` to skip his transactions and overnight it went through and processed them all.

**Comment by rickles42** [comment]
@PseudonymPatel What you described is actually pretty much how the transactions are stored and processed today! Only instead of a dictionary, we are using an external database, which makes it easier to persist transactions between upgrades of the system.

Essentially, every time the `bot` agent processes a `!invest` command, it adds a row to our Investments table, which includes the name of the user, the ID of the post they invested in, time of the investment, etc.

Separately, the `calculator` agent periodically queries that table for investments whose age is great enough, checks back in on the post, compares upvotes, calculates return, and posts the results back to the user.
